import { readFile } from "fs/promises";
import { prisma } from "../../src/db";
import { log, parseArgs, argString } from "../script-utils";

/**
 * Script to enqueue REFUND jobs from the CSV generated by identify-refund-discrepancies.ts
 *
 * Only creates jobs for purchases that don't already have active REFUND jobs
 * (i.e., where existing_refund_job column is empty)
 */

type CSVRow = {
  purchase_id: string;
  x402_nonce: string;
  payer: string;
  recipient: string;
  usdc_amount_6d: string;
  usdc_amount_decimal: string;
  token_lower: string;
  onchain_id: string;
  current_status: string;
  payment_tx_hash: string;
  payment_block_number: string;
  purchase_tx_hash: string;
  refund_tx_hash: string;
  existing_refund_job: string;
  reason: string;
  created_at: string;
};

function parseCSV(csvContent: string): CSVRow[] {
  const lines = csvContent.trim().split("\n");
  if (lines.length < 2) {
    throw new Error("CSV is empty or has no data rows");
  }

  const headers = lines[0].split(",");
  const rows: CSVRow[] = [];

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];

    // Handle quoted fields (reason field has quotes)
    const values: string[] = [];
    let currentValue = "";
    let insideQuotes = false;

    for (let j = 0; j < line.length; j++) {
      const char = line[j];

      if (char === '"') {
        insideQuotes = !insideQuotes;
      } else if (char === ',' && !insideQuotes) {
        values.push(currentValue);
        currentValue = "";
      } else {
        currentValue += char;
      }
    }
    values.push(currentValue); // Push last value

    if (values.length !== headers.length) {
      log.warn({ line: i + 1, expected: headers.length, got: values.length }, "Skipping malformed row");
      continue;
    }

    const row: any = {};
    for (let j = 0; j < headers.length; j++) {
      row[headers[j]] = values[j];
    }
    rows.push(row as CSVRow);
  }

  return rows;
}

async function main() {
  const args = parseArgs();
  const csvPath = argString(args, "csv") || "refund-discrepancies.csv";
  const dryRun = argString(args, "dry-run") === "true";

  log.info({ csvPath, dryRun }, "Starting REFUND job creation from CSV");

  // Read CSV
  const csvContent = await readFile(csvPath, "utf-8");
  const rows = parseCSV(csvContent);

  log.info({ totalRows: rows.length }, "CSV parsed");

  // Filter for rows that need action (no existing refund job)
  const needsRefundJob = rows.filter(row => !row.existing_refund_job || row.existing_refund_job.startsWith("dead:"));
  const alreadyHasJob = rows.filter(row => row.existing_refund_job && !row.existing_refund_job.startsWith("dead:"));

  console.log("\n=== REFUND JOB CREATION SUMMARY ===\n");
  console.log(`Total rows in CSV: ${rows.length}`);
  console.log(`Already has active job: ${alreadyHasJob.length}`);
  console.log(`Needs REFUND job: ${needsRefundJob.length}\n`);

  if (needsRefundJob.length === 0) {
    console.log("✅ No REFUND jobs need to be created. All purchases already have active jobs.");
    return;
  }

  // Calculate total USDC for jobs to be created
  let totalUsdc = 0n;
  for (const row of needsRefundJob) {
    totalUsdc += BigInt(row.usdc_amount_6d);
  }

  console.log(`Total USDC to refund: $${(parseFloat(totalUsdc.toString()) / 1e6).toFixed(2)}\n`);

  // Group by status
  const byStatus: Record<string, number> = {};
  for (const row of needsRefundJob) {
    byStatus[row.current_status] = (byStatus[row.current_status] || 0) + 1;
  }

  console.log("By current status:");
  for (const [status, count] of Object.entries(byStatus)) {
    console.log(`  - ${status}: ${count}`);
  }
  console.log();

  if (dryRun) {
    console.log("🔍 DRY RUN - No changes will be made\n");
    console.log("Jobs that would be created (first 10):\n");

    for (const row of needsRefundJob.slice(0, 10)) {
      console.log(`Purchase: ${row.purchase_id}`);
      console.log(`  Status: ${row.current_status}`);
      console.log(`  Payer: ${row.payer}`);
      console.log(`  Amount: $${row.usdc_amount_decimal}`);
      console.log(`  Reason: ${row.reason}`);
      console.log(`  Unique Key: refund:${row.x402_nonce}`);
      console.log();
    }

    console.log("\nTo actually create the jobs, run without --dry-run true");
    return;
  }

  // Confirm before proceeding
  console.log(`⚠️  About to create ${needsRefundJob.length} REFUND jobs`);
  console.log("This will:");
  console.log("  1. Insert jobs into the jobs table");
  console.log("  2. Update purchase status to 'to_refund' if not already");
  console.log("");

  // Create jobs
  let created = 0;
  let skipped = 0;
  let updated = 0;

  for (const row of needsRefundJob) {
    const uniqueKey = `refund:${row.x402_nonce}`;

    try {
      // Check if job already exists (extra safety)
      const existingJob = await prisma.job.findUnique({
        where: {
          kind_uniqueKey: {
            kind: "REFUND",
            uniqueKey: uniqueKey
          }
        }
      });

      if (existingJob) {
        log.info({ purchaseId: row.purchase_id, jobId: existingJob.id }, "Job already exists, skipping");
        skipped++;
        continue;
      }

      // Update purchase status to to_refund if needed
      if (row.current_status !== "to_refund") {
        await prisma.purchase.update({
          where: { id: row.purchase_id },
          data: { status: "to_refund" }
        });
        updated++;
        log.info({ purchaseId: row.purchase_id, oldStatus: row.current_status }, "Updated status to to_refund");
      }

      // Create REFUND job
      await prisma.job.create({
        data: {
          kind: "REFUND",
          uniqueKey: uniqueKey,
          payload: {
            purchaseId: row.purchase_id,
            tokenLower: row.token_lower,
            payer: row.payer,
            usdcAmount6d: row.usdc_amount_6d
          },
          status: "queued",
          maxAttempts: 3
        }
      });

      created++;
      log.info({ purchaseId: row.purchase_id, uniqueKey }, "REFUND job created");

      // Progress indicator
      if (created % 10 === 0) {
        console.log(`Progress: ${created}/${needsRefundJob.length} jobs created...`);
      }

    } catch (err: any) {
      log.error({ err, purchaseId: row.purchase_id }, "Failed to create job");

      if (err.code === "P2002") {
        // Unique constraint violation - job already exists
        skipped++;
      } else {
        throw err;
      }
    }
  }

  console.log("\n✅ REFUND JOB CREATION COMPLETE\n");
  console.log(`Jobs created: ${created}`);
  console.log(`Jobs skipped (already exist): ${skipped}`);
  console.log(`Purchase status updated: ${updated}`);
  console.log(`Total USDC amount: $${(parseFloat(totalUsdc.toString()) / 1e6).toFixed(2)}\n`);

  if (created > 0) {
    console.log("Next steps:");
    console.log("1. Monitor worker logs: pm2 logs vending-worker");
    console.log("2. Check job status: SELECT status, COUNT(*) FROM jobs WHERE kind='REFUND' GROUP BY status;");
    console.log("3. Run identify-refund-discrepancies.ts again to verify");
  }
}

main()
  .catch((err) => {
    log.error({ err }, "Script error");
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
