module.exports = {
  apps: [
    {
      name: 'vending-api',
      script: 'bun',
      args: 'src/vending-api.ts',
      cwd: '/home/appuser/x402-vending-machine',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PORT: '8080',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: '/home/appuser/.pm2/logs/vending-api-error.log',
      out_file: '/home/appuser/.pm2/logs/vending-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'public-api',
      script: 'bun',
      args: 'src/public-api.ts',
      cwd: '/home/appuser/x402-vending-machine',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PUBLIC_PORT: '8082',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/appuser/.pm2/logs/public-api-error.log',
      out_file: '/home/appuser/.pm2/logs/public-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'internal-api',
      script: 'bun',
      args: 'src/internal-api.ts',
      cwd: '/home/appuser/x402-vending-machine',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        INTERNAL_PORT: '8081',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/appuser/.pm2/logs/internal-api-error.log',
      out_file: '/home/appuser/.pm2/logs/internal-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'vending-worker',
      script: 'bun',
      args: 'src/vending-worker.ts',
      cwd: '/home/appuser/x402-vending-machine',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: '/home/appuser/.pm2/logs/vending-worker-error.log',
      out_file: '/home/appuser/.pm2/logs/vending-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
